#!/bin/bash

install() {
  # prepare vars
  local name="$DESKTOP_CORE_NAME"

  log::info "[$(timestamp)][desktop][$name] preparing ..."

  # get system os/arch
  local os="$DESKTOP_OS"
  local arch="$DESKTOP_OS_ARCH"
  local kernel="$DESKTOP_OS_KERNEL"
  local platform="$DESKTOP_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$DESKTOP_USER_BIN_DIR"
  local tmp_dir="$DESKTOP_TMP_DIR"

  #
  case $platform in
  darwin) ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  # case $arch in
  # arm64) ;;

  # amd64)
  #   arch="x86_64"
  #   ;;
  # *)
  #   log::error "[$(timestamp)] unsupport arch: $arch"
  #   return 1
  #   ;;
  # esac
  # #

  # files
  local tmp_file="$name.zip"
  # local source_bin_file="./$name"

  # prepare context
  cd $tmp_dir

  local dv=$(echo ${DESKTOP_CORE_VERSION#v} | sed 's/\./_/g')
  # reference: https://github.com/9seconds/iterm2/releases
  # example:
  #   https://iterm2.com/downloads/stable/iTerm2-3_4_19.zip
  # generate url
  local url="${DESKTOP_CORE_RELEASE_DOWNLOAD}/stable/iTerm2-${dv}.zip"
  log::debug "[$(timestamp)][desktop][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][desktop][$name] downloading ..."
  os::download $tmp_file $url

  # install
  log::info "[$(timestamp)][desktop][$name] installing ..."
  # os::install $source_bin_file $usr_bin_dir $name
  install::zip $tmp_file

  # clean
  log::info "[$(timestamp)][desktop][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
